fix: Remove missed _add_comment_to_deal call at line 402
Found one remaining call to _add_comment_to_deal() that was missed in the
previous refactoring commit. This method was removed but one call remained.

Error: AttributeError: 'SyncOrchestrator' object has no attribute '_add_comment_to_deal'
Fixed: Removed the call from line 402 (create new deal case)